### ISSUE TITLE
New version 8.048.03 was released

### ISSUE THREAD

**Issue by thimslugga** [mtorromeo/r8168#28]
Realtek version 8.048.03 was released on 05-25-2020. I threw it up on filebin since Realtek has that silly email and captcha..

https://filebin.net/m8fz1f13f1xz4pt5/r8168-8.048.03.tar.bz2?t=praxtncs

$ md5sum r8168-8.048.03.tar.bz2 
216f745af9d871784eaffa06ce9a1632  r8168-8.048.03.tar.bz2

https://www.realtek.com/zh-tw/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software

**Comment by mtorromeo** [comment]
Imported, thanks!
