### ISSUE TITLE
Please fix suspected non-free binary code in r8168_n.c

### ISSUE THREAD

**Issue by btegs** [mtorromeo/r8168#3]
As specified in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=787634 and https://devel.trisquel.info/trisquel/ubuntu-purge/merge_requests/17, the r8168_n.c file in /src/ contains a binary blob without source code provided.

Please provide source code for the suspected non-free binary code or find a way to make the firmware usable without it. Your code is labeled as GPL, but not all of it is. Thank you.

**Comment by mtorromeo** [comment]
Thanks for pointing it out, and I'm all for free software, but this is NOT my code. I'm merely mirroring it here since the Realtek website has some serious accessibility issues.

You should direct your concerns to Realtek.
