### ISSUE TITLE
Kernel-5.17rc

### ISSUE THREAD

**Issue by petehg** [mtorromeo/r8168#38]
I'm sorry but I forked your project and didn't intend to.
What I wanted was to check if you looked at compiling with the latest kernel.
It won't compile with k5.17 and although I've looked at it I don't know enough to get round the main changes.
Have you looked into it yet?
I have the error list in a differnt system and I can send you it if needed.
pete

**Comment by petehg** [comment]
I've made a work around patch for now. I'm not sure it's ideal but it works with kernel-5.16 and kernel-5.17rc1/2.
`--- a/r8168_n.c	2021-07-05 01:30:48.000000000 +0100
+++ b/r8168_n.c	2022-02-02 09:13:11.165555448 +0000
@@ -95,6 +95,10 @@
 #include <linux/seq_file.h>
 #endif
 
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 17, 0))
+#define PDE_DATA pde_data
+#endif
+
 #define FIRMWARE_8168D_1    "rtl_nic/rtl8168d-1.fw"
 #define FIRMWARE_8168D_2    "rtl_nic/rtl8168d-2.fw"
 #define FIRMWARE_8168E_1    "rtl_nic/rtl8168e-1.fw"
@@ -523,6 +527,12 @@
 
 MODULE_VERSION(RTL8168_VERSION);
 
+#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 15, 0)
+static inline void dev_addr_mod(struct net_device *dev, unsigned int offset, const void *addr, size_t len) {
+	memcpy(&dev->dev_addr[offset], addr, len);
+}
+#endif
+
 static void rtl8168_sleep_rx_enable(struct net_device *dev);
 static void rtl8168_dsm(struct net_device *dev, int dev_state);
 
@@ -24127,11 +24137,12 @@
         }
 
         rtl8168_rar_set(tp, mac_addr);
-
+#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 17, 0)
         for (i = 0; i < MAC_ADDR_LEN; i++) {
                 dev->dev_addr[i] = RTL_R8(tp, MAC0 + i);
                 tp->org_mac_addr[i] = dev->dev_addr[i]; /* keep the original MAC address */
         }
+#endif        
 #if LINUX_VERSION_CODE > KERNEL_VERSION(2,6,13)
         memcpy(dev->perm_addr, dev->dev_addr, dev->addr_len);
 #endif
@@ -24159,8 +24170,8 @@
                 return -EADDRNOTAVAIL;
 
         spin_lock_irqsave(&tp->lock, flags);
-
-        memcpy(dev->dev_addr, addr->sa_data, dev->addr_len);
+        dev_addr_mod(dev, 0, addr->sa_data, dev->addr_len);
+       /* memcpy(dev->dev_addr, addr->sa_data, dev->addr_len);*/
 
         rtl8168_rar_set(tp, dev->dev_addr);`

**Comment by petehg** [comment]
I've no idea why that won't show up correctly. It's supposed to be a straight copy of my patch. But I hope anyone will get the gist.

**Comment by petehg** [comment]
@@ -24127,11 +24137,12 @@
         }
 
         rtl8168_rar_set(tp, mac_addr);
-
+#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 17, 0)
         for (i = 0; i < MAC_ADDR_LEN; i++) {
                 dev->dev_addr[i] = RTL_R8(tp, MAC0 + i);
                 tp->org_mac_addr[i] = dev->dev_addr[i]; /* keep the original MAC address */
         }
+#endif        
 #if LINUX_VERSION_CODE > KERNEL_VERSION(2,6,13)
         memcpy(dev->perm_addr, dev->dev_addr, dev->addr_len);
 #endif
@@ -24159,8 +24170,8 @@
                 return -EADDRNOTAVAIL;
 
         spin_lock_irqsave(&tp->lock, flags);
-
-        memcpy(dev->dev_addr, addr->sa_data, dev->addr_len);
+        dev_addr_mod(dev, 0, addr->sa_data, dev->addr_len);
+       /* memcpy(dev->dev_addr, addr->sa_data, dev->addr_len);*/
 
         rtl8168_rar_set(tp, dev->dev_addr);

**Comment by petehg** [comment]
--- a/r8168_n.c	2021-07-05 01:30:48.000000000 +0100
+++ b/r8168_n.c	2022-02-02 09:13:11.165555448 +0000
@@ -95,6 +95,10 @@
 #include <linux/seq_file.h>
 #endif
 
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 17, 0))
+#define PDE_DATA pde_data
+#endif
+
 #define FIRMWARE_8168D_1    "rtl_nic/rtl8168d-1.fw"
 #define FIRMWARE_8168D_2    "rtl_nic/rtl8168d-2.fw"
 #define FIRMWARE_8168E_1    "rtl_nic/rtl8168e-1.fw"
@@ -523,6 +527,12 @@
 
 MODULE_VERSION(RTL8168_VERSION);
 
+#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 15, 0)
+static inline void dev_addr_mod(struct net_device *dev, unsigned int offset, const void *addr, size_t len) {
+	memcpy(&dev->dev_addr[offset], addr, len);
+}
+#endif
+
 static void rtl8168_sleep_rx_enable(struct net_device *dev);
 static void rtl8168_dsm(struct net_device *dev, int dev_state);
 
@@ -24127,11 +24137,12 @@
         }
 
         rtl8168_rar_set(tp, mac_addr);
-
+#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 17, 0)
         for (i = 0; i < MAC_ADDR_LEN; i++) {
                 dev->dev_addr[i] = RTL_R8(tp, MAC0 + i);
                 tp->org_mac_addr[i] = dev->dev_addr[i]; /* keep the original MAC address */
         }
+#endif        
 #if LINUX_VERSION_CODE > KERNEL_VERSION(2,6,13)
         memcpy(dev->perm_addr, dev->dev_addr, dev->addr_len);
 #endif
@@ -24159,8 +24170,8 @@
                 return -EADDRNOTAVAIL;
 
         spin_lock_irqsave(&tp->lock, flags);
-
-        memcpy(dev->dev_addr, addr->sa_data, dev->addr_len);
+        dev_addr_mod(dev, 0, addr->sa_data, dev->addr_len);
+       /* memcpy(dev->dev_addr, addr->sa_data, dev->addr_len);*/
 
         rtl8168_rar_set(tp, dev->dev_addr);

**Comment by petehg** [comment]
--- a/r8168_n.c	2021-07-05 01:30:48.000000000 +0100
+++ b/r8168_n.c	2022-02-02 09:13:11.165555448 +0000
@@ -95,6 +95,10 @@
 #include <linux/seq_file.h>
 #endif
 
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 17, 0))
+#define PDE_DATA pde_data
+#endif
+
 #define FIRMWARE_8168D_1    "rtl_nic/rtl8168d-1.fw"
 #define FIRMWARE_8168D_2    "rtl_nic/rtl8168d-2.fw"
 #define FIRMWARE_8168E_1    "rtl_nic/rtl8168e-1.fw"
@@ -523,6 +527,12 @@
 
 MODULE_VERSION(RTL8168_VERSION);
 
+#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 15, 0)
+static inline void dev_addr_mod(struct net_device *dev, unsigned int offset, const void *addr, size_t len) {
+	memcpy(&dev->dev_addr[offset], addr, len);
+}
+#endif
+
 static void rtl8168_sleep_rx_enable(struct net_device *dev);
 static void rtl8168_dsm(struct net_device *dev, int dev_state);
 
@@ -24127,11 +24137,12 @@
         }
 
         rtl8168_rar_set(tp, mac_addr);
-
+#if LINUX_VERSION_CODE < KERNEL_VERSION(5, 17, 0)
         for (i = 0; i < MAC_ADDR_LEN; i++) {
                 dev->dev_addr[i] = RTL_R8(tp, MAC0 + i);
                 tp->org_mac_addr[i] = dev->dev_addr[i]; /* keep the original MAC address */
         }
+#endif        
 #if LINUX_VERSION_CODE > KERNEL_VERSION(2,6,13)
         memcpy(dev->perm_addr, dev->dev_addr, dev->addr_len);
 #endif
@@ -24159,8 +24170,8 @@
                 return -EADDRNOTAVAIL;
 
         spin_lock_irqsave(&tp->lock, flags);
-
-        memcpy(dev->dev_addr, addr->sa_data, dev->addr_len);
+        dev_addr_mod(dev, 0, addr->sa_data, dev->addr_len);
+       /* memcpy(dev->dev_addr, addr->sa_data, dev->addr_len);*/
 
         rtl8168_rar_set(tp, dev->dev_addr);

**Comment by redpig888** [comment]
Hi petehg, can I give me your modified files? Thank you

**Comment by eskuai** [comment]
Hi @petehg 

I've applied yout patch file against 5.17 final , and it runs but doesn't work ... 
Running on fedora 35,  deploy modele but it seems in a loop ... network is not reachable..
autorun  shows:

```
Check old driver and unload it.
rmmod r8168
Build the module and install
/nvme/r8168-8.049.02/src/r8168_n.c: In function ‘rtl8168_set_mac_address’:
/nvme/r8168-8.049.02/src/r8168_n.c:24179:32: warning: passing argument 2 of ‘rtl8168_rar_set’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
24179 |         rtl8168_rar_set(tp, dev->dev_addr);
      |                             ~~~^~~~~~~~~~
/nvme/r8168-8.049.02/src/r8168_n.c:576:59: note: expected ‘uint8_t *’ {aka ‘unsigned char *’} but argument is of type ‘const unsigned char *’
  576 | void rtl8168_rar_set(struct rtl8168_private *tp, uint8_t *addr);
      |                                                  ~~~~~~~~~^~~~
/nvme/r8168-8.049.02/src/r8168_n.c: In function ‘rtl8168_resume’:
/nvme/r8168-8.049.02/src/r8168_n.c:28664:32: warning: passing argument 2 of ‘rtl8168_rar_set’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
28664 |         rtl8168_rar_set(tp, dev->dev_addr);
      |                             ~~~^~~~~~~~~~
/nvme/r8168-8.049.02/src/r8168_n.c:24194:26: note: expected ‘uint8_t *’ {aka ‘unsigned char *’} but argument is of type ‘const unsigned char *’
24194 |                 uint8_t *addr)
      |                 ~~~~~~~~~^~~~
DEPMOD 5.17.0
load module r8168
Completed.
```
but, anyway, no network ..

any help please?

Tx

**Comment by petehg** [comment]
I'm afraid it's stopped working for me too. I did say it wasn't ideal it was meant as a work-around. Unfortunately it hasn't kept up with the full release.
Perhaps someone who knows more than I can find a fix.
In the meantime I'm using r8169 included in the kernel. I've not found it totally satisfactory in the past but maybe it's improved.

**Comment by kelebek333** [comment]
Below patch is working on Linux Mint/Ubuntu base with Linux 5.15 or 5.17. This based that. https://github.com/archlinux/svntogit-community/blob/packages/r8168/trunk/linux517.patch

```

diff -Naru a/src/r8168_n.c b/src/r8168_n.c
--- a/src/r8168_n.c
+++ b/src/r8168_n.c
@@ -1733,7 +1733,11 @@
 static int rtl8168_proc_open(struct inode *inode, struct file *file)
 {
         struct net_device *dev = proc_get_parent_data(inode);
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 17, 0))
+        int (*show)(struct seq_file *, void *) = pde_data(inode);
+#else
         int (*show)(struct seq_file *, void *) = PDE_DATA(inode);
+#endif
 
         return single_open(file, show, dev);
 }
@@ -24061,6 +24065,9 @@
         struct rtl8168_private *tp = netdev_priv(dev);
         int i;
         u8 mac_addr[MAC_ADDR_LEN];
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 17, 0))
+        u8 addr[ETH_ALEN];
+#endif
 
         for (i = 0; i < MAC_ADDR_LEN; i++)
                 mac_addr[i] = RTL_R8(tp, MAC0 + i);
@@ -24129,9 +24136,16 @@
         rtl8168_rar_set(tp, mac_addr);
 
         for (i = 0; i < MAC_ADDR_LEN; i++) {
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 17, 0))
+                addr[i] = RTL_R8(tp, MAC0 + i);
+#else
                 dev->dev_addr[i] = RTL_R8(tp, MAC0 + i);
+#endif
                 tp->org_mac_addr[i] = dev->dev_addr[i]; /* keep the original MAC address */
         }
+#if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 17, 0))
+        eth_hw_addr_set(dev, addr);
+#endif
 #if LINUX_VERSION_CODE > KERNEL_VERSION(2,6,13)
         memcpy(dev->perm_addr, dev->dev_addr, dev->addr_len);
 #endif

```

**Comment by petehg** [comment]
Thanks kelebek33. I'll give this a try and let you know how it goes. It'll be opensuse in addition to your tests.
