### ISSUE TITLE
Kernel-5.19-rc1 patch

### ISSUE THREAD

**Issue by petehg** [mtorromeo/r8168#45]
I've a new patch for r8168_n.c with kernel-5.19.xx. I've only been able to test it on rc1 of course but it also works with kernel-5.18.2x.
```
--- r8168_n.c	2022-05-06 10:57:21.505281694 +0100
+++ r8168_n.c	2022-06-07 19:23:22.096066995 +0100
@@ -26834,7 +26834,11 @@
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(2,6,22)
                 if ((tp->mcfg == CFG_METHOD_1) || (tp->mcfg == CFG_METHOD_2) || (tp->mcfg == CFG_METHOD_3)) {
                         dev->hw_features &= ~NETIF_F_IPV6_CSUM;
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,19,0)
+                        netif_set_tso_max_size(dev, LSO_32K);
+#else
                         netif_set_gso_max_size(dev, LSO_32K);
+#endif //LINUX_VERSION_CODE >= KERNEL_VERSION(5,19,0)
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(3,18,0)
                         dev->gso_max_segs = NIC_MAX_PHYS_BUF_COUNT_LSO_64K;
 #if LINUX_VERSION_CODE < KERNEL_VERSION(4,7,0)
@@ -26848,7 +26852,11 @@
                                 dev->hw_features |= NETIF_F_TSO6;
                                 //dev->features |=  NETIF_F_TSO6;
                         }
-                        netif_set_gso_max_size(dev, LSO_64K);
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,19,0)
+                        netif_set_tso_max_size(dev, LSO_32K);
+#else
+                        netif_set_gso_max_size(dev, LSO_32K);
+#endif //LINUX_VERSION_CODE >= KERNEL_VERSION(5,19,0)
 #if LINUX_VERSION_CODE >= KERNEL_VERSION(3,18,0)
                         dev->gso_max_segs = NIC_MAX_PHYS_BUF_COUNT_LSO2;
 #if LINUX_VERSION_CODE < KERNEL_VERSION(4,7,0)
```

**Comment by superherointj** [comment]
Why not to make a PR instead?

**Comment by petehg** [comment]
Because people may not see my set up but they are likely to look in issues to see if there are answers.

**Comment by superherointj** [comment]
Humm... Search can search in both issues and PR.

I find PRs better because of:
* It's easier to fetch the patch. (by url, by adding `.patch` at end)
* Upstream being able to test and merge your changes directly without having to resort to making a new PR and copying and pasting your work.

Anyway, thanks for the contributions you have been providing. That is certainly helpful to many.

**Comment by alexclang** [comment]
I guess I'm missing the point of not merging the patch into the main branch. I just go a "git pull" and if the code changes, I rerun "autorun". I do all this in a shell script at boot time. 

Stated another way, shouldn't all patches be merged into master at some point?

**Comment by petehg** [comment]
Why the fuss? I created this for me then thought I'd share it. Use it or don't use it.

**Comment by superherointj** [comment]
> Why the fuss? I created this for me then thought I'd share it. Use it or don't use it.

No fuss. Thanks for sharing your code.

**Comment by petehg** [comment]
> No fuss. Thanks for sharing your code.
You're welcome.
Incidentally the patch works with kernel-6-rc.

**Comment by petehg** [comment]
> > Why the fuss? I created this for me then thought I'd share it. Use it or don't use it.
> 
> No fuss. Thanks for sharing your code.

You're welcome.
Incidentally, the patch still works with kernel-6-rc.
