### ISSUE TITLE
Fix for PopOS latest kernel 6.1.11 compile failure

### ISSUE THREAD

**Issue by vijinho** [mtorromeo/r8168#49]
Remove the last parameter `weight` in `r8168.h` to make the module compile with PopOS 6.1.11

`6.1.11-76060111-generic #202302091138~1675975749~22.04~f771a7f SMP PREEMPT_DYNAMIC Thu F x86_64 x86_64 x86_64 GNU/Linux`

```
-#define RTL_NAPI_CONFIG(ndev, priv, function, weight)   netif_napi_add(ndev, &priv->napi, function, weight)
+#define RTL_NAPI_CONFIG(ndev, priv, function, weight)   netif_napi_add(ndev, &priv->napi, function)
```

**Comment by teeedubb** [comment]
Thanks for posting this.
Just adding that these changes enable compiling and installation on ubuntu 22.04.1 with the 6.2.0-26-generic kernel.
