### ISSUE TITLE
8.042 is out

### ISSUE THREAD

**Issue by lars18th** [mtorromeo/r8168#5]
Can you upgrade?

http://www.realtek.com.tw/downloads/downloadsView.aspx?Langid=1&PNid=5&PFid=5&Level=5&Conn=4&DownTypeID=3&GetDown=false#RTL8111B/RTL8168B/RTL8111/RTL8168<br>RTL8111C/RTL8111CP/RTL8111D(L)<br>RTL8168C/RTL8111DP/RTL8111E<br>RTL8168E/RTL8111F/RTL8411<br>RTL8111G/RTL8111GUS/RTL8411B(N)<br>RTL8118AS

**Comment by mtorromeo** [comment]
Tagged vedrsion 8.042. Thanks!
